name: cliar
description: Cliar (クリアー) は、dart のクラス定義からコマンドラインオプションを設定できるようにするパッケージです。
version: 0.1.0
repository: https://github.com/booink/cliar-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  recase: ^4.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
